### PR TITLE
Support for creating new tox environments

### PR DESCRIPTION
**Pull request by se02035**
Create tox envs based on configurable env templates.
  - Added new VSCode config section (`python-tox.environment.template.new`) to specify env templates
  - Env templates support token replacements (using lodash)
  - Added automated tests (incl mocks where user input is required)
  - Updated doc (README.md)

### CODE REVIEW

**Comment by se02035** [comment]
@The-Compiler , if you need more information / support to review the PR, please let me know. Happy to help merging the improvements.

**Comment by The-Compiler** [comment]
@se02035 @pkirch @dariuszparys @starlord-daniel Sorry for the loooong delay! This project is something I started to scratch an itch and dabble into Typescript (never used Typescript before, other than a few trivial contributions to other VS Code extensions). I'm glad to hear you find it useful as well and love the contributions, but I totally didn't expect this to happen at all!

Thus, the idea of reviewing so much code in a language I'm quite new to feels quite overwhelming (and there also were some bigger changes in my [main project](https://qutebrowser.org) I wanted to finish first - like those things sometimes go, they took a bit longer than anticipated...).

This is all still on my radar, and I plan to take a first look at the PRs today. Hoping that I can already merge some (or even all - we will see!), but I might also have some questions first here and there. Thanks for your patience! :sweat_smile:

**Comment by The-Compiler** [comment]
Reopening to hopefully trigger CI after f7791a249e1db738e43d0982981bd106eb60cd4f.

**Comment by The-Compiler** [comment]
I have a preliminary merge of this into the latest `main` in the [`merge-snippets` branch](https://github.com/The-Compiler/vscode-python-tox/compare/merge-snippets).

However, after reading through the code and trying the functionality out, I wonder: Isn't this just essentially reinventing the wheel for something which would served much better with an existing VS Code feature, [snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets)?

They would allow you to do pretty much the same thing, but in a much more interactive way - not only with placeholders for the environment name like now, but also with other placeholders in the template where needed.

@se02035 am I missing something there? Could you elaborate on your use-case for this a bit more?

**Comment by The-Compiler** [comment]
Closing this for now - happy to reconsider if you have an use-case I'm missing which can't be solved in a better way with VS Code snippets.

**Pull request closed without merging**
